AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
    Default: api

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET

  DatabaseDataLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: data/

  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: !Ref Env
      CodeUri: dist/search.zip
      Handler: hello
      MemorySize: 256
      Timeout: 30
      Runtime: provided
      Layers:
        - !Ref DatabaseDataLayer
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /search
            PayloadFormatVersion: "1.0"

  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: !Ref Env
      CodeUri: dist/list.zip
      Handler: lambda_handler
      MemorySize: 256
      Timeout: 30
      Runtime: provided
      Layers:
        - !Ref DatabaseDataLayer
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /list
            PayloadFormatVersion: "1.0"
