AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
    Default: api

  DataTableName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ffxiv-item-name-database/item-data-table-name

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET

  DatabaseDataLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: data/

  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: !Ref Env
      CodeUri: dist/search.zip
      Handler: hello
      MemorySize: 256
      Timeout: 30
      Runtime: provided
      Layers:
        - !Ref DatabaseDataLayer
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /search
            PayloadFormatVersion: "1.0"

  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: !Ref Env
      CodeUri: dist/list.zip
      Handler: lambda_handler
      MemorySize: 256
      Timeout: 30
      Runtime: provided
      Layers:
        - !Ref DatabaseDataLayer
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /list
            PayloadFormatVersion: "1.0"

  ListV2Function:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: !Ref Env
      CodeUri: dist/list.zip
      Handler: lambda_handler
      MemorySize: 256
      Timeout: 30
      Runtime: provided
      Environment:
        Variables:
          TABLE_NAME: !Ref DataTableName
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /list/v2
            PayloadFormatVersion: "1.0"

  DynamoDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: !Ref Env
      CodeUri: dist/dynamodb.zip
      Handler: lambda_handler
      MemorySize: 256
      Timeout: 30
      Runtime: provided
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /dynamodb
            PayloadFormatVersion: "1.0"

  SSMParameterApiUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com
      Name: /ffxiv-item-name-database/api/api-url

Outputs:
  SSMParameterNameApiUrl:
    Value: !Ref SSMParameterApiUrl

  ApiUrl:
    Value: !GetAtt SSMParameterApiUrl.Value