AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  DataTableName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ffxiv-item-name-database/item-data-table-name

  ApiOriginPath:
    Type: String
    Default: api

Globals:
  Function:
    AutoPublishAlias: api
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        TABLE_NAME: !Ref DataTableName

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        AllowMethods:
          - GET

  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/search.zip
      Handler: lambda_handler
      Runtime: provided
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: $Sub /${ApiOriginPath}/search
            PayloadFormatVersion: "1.0"

  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/list.zip
      Handler: lambda_handler
      Runtime: provided
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: $Sub /${ApiOriginPath}/list
            PayloadFormatVersion: "1.0"

  PythonSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python/
      Handler: search.handler
      Runtime: python3.8
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /python/search
            PayloadFormatVersion: "1.0"

  PythonListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: python/
      Handler: list.handler
      Runtime: python3.8
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Method: GET
            Path: /python/list
            PayloadFormatVersion: "1.0"

  SSMParameterApiDomainName:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Sub ${HttpApi}.execute-api.${AWS::Region}.amazonaws.com
      Name: /ffxiv-item-name-database/api/api-domain-name

  SSMParameterApiUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Sub https://${SSMParameterApiDomainName.Value}
      Name: /ffxiv-item-name-database/api/api-url

  SSMParameterApiOriginPath:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !Ref ApiOriginPath
      Name: /ffxiv-item-name-database/api/api-origin-path

Outputs:
  SSMParameterNameApiDomainName:
    Value: !Ref SSMParameterApiDomainName

  SSMParameterNameApiUrl:
    Value: !Ref SSMParameterApiUrl

  ApiUrl:
    Value: !GetAtt SSMParameterApiUrl.Value

  SSMParameterNameApiOriginPath:
    Value: !Ref SSMParameterApiOriginPath

